M48
; DRILL file {KiCad (7.0.0)} date Sun 05 Mar 2023 07:46:50 PM CET
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-03-05T19:46:50+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(7.0.0)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.200
%
G90
G05
T1
X94.06Y-54.022
X94.06Y-56.522
X99.06Y-49.022
X104.06Y-54.022
X104.06Y-56.522
T0
M30
